FROM python:3.11

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install dependencies
RUN pip install pipenv
COPY Pipfile.lock /code
COPY Pipfile /code
RUN pipenv install

# run container
COPY . /code
EXPOSE 1213
ENTRYPOINT ["sh", "entrypoint.sh" ]