# two services
#   services has custom network

# backend
#   container should restart always
#   container should use volume

# database
#   use docker-compose file from postgres_data
version: "3.9"
services:

  backend:
    build:
      context: ./new_blog_app
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./new_blog_app:/code
    depends_on:
      - postgres


  #postgres:
  #  extends:
  #    file: ./postgresql/docker-compose.yaml
  #    service: postgres


  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "new_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5433"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./backups/:/home/container_folder_dump/
