# two services
version: "3.9"
services:

  # backend
  backend:
    restart: always
    build:
      context: ./new_blog_app
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    #   container should use volume
    volumes:
      - ./new_blog_app:/code
    depends_on:
      - postgres
    networks:
      blog_network:
        ipv4_address: 10.1.12.3


  # database
  postgres:
    #   use docker-compose file from postgres_data
    extends:
      file: ./postgresql/docker-compose.yaml
      service: postgres
    networks:
      blog_network:
        ipv4_address: 10.1.12.2

#   services has custom network
networks:
  blog_network:
    ipam:
      driver: default
      config:
        - subnet: 10.1.12.0/24