version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "new_db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5433"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./backups/:/home/container_folder_dump/

